[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
open_house_redone = "J4B6mY3BfhpXmthVpdY6R315RTKxQnzitjYafwQZ8he"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
